### PR TITLE
Add launch mechanism for DAWN projects, command for adding nature

### PR DESCRIPTION
**Pull request by turesheim**
Note that the launch bar is not part of this contribution. It is kept in a separate repository and the changes I've made to this has been or is being merged into the eclipse.org repository. It should at some time be available as a dependency, meanwhile the fork at https://github.com/Itema-as/org.eclipse.launchbar/tree/tweaks. No configuration is required, only to add it to the product.

### CODE REVIEW

**Comment by turesheim** [comment]
Also note that for the *Launch Bar* to work, it must be running on Eclipse 4. Launching a DAWN product will still work without it.

**Comment by turesheim** [comment]
The toolbar showing the *Launch Bar*
skjermbilde 2015-10-25 kl 23 52 02

**Comment by gerring** [comment]
Nice. Perhaps you can walkthrough some of the features with me when we next VC or meet @ Diamond.

**Comment by turesheim** [comment]
I'll be glad to :-)

**Pull request merged**
