### PR TITLE
Add wizard for new DAWN extension projects, UI for project nature.

### PR DESCRIPTION
**Pull request by turesheim**

### CODE REVIEW

**Comment by gerring** [comment]
Where does @NonNull come from? I cannot seem to find the annotation in Java7. Is it a Java8 thing? - looks handy...

**Comment by turesheim** [comment]
Yes, it's in Java 8. But since the BREE is Java 7 I've included *org.eclipse.jdt.annotation* which includes these. The annotations can easily be replaced with the Java 8 versions by updating the BREE and remove the dependency.

**Comment by gerring** [comment]
We have both an e3 and e4 target. Is org.eclipse.jdt.annotation going to work, I assume it will.

**Comment by turesheim** [comment]
Yes. However it should be removed for the Eclipse Neon target as that will be based on Java 8.

**Pull request merged**
